In [2]:
import numpy as np
import pandas as pd
import pyreadstat
import matplotlib.pyplot as plt
from sas7bdat import SAS7BDAT
from tableone import TableOne

In [3]:
demographics_niss_df = pd.read_csv("/Volumes/Research/GoldenHourData/InclusionCriteria/demographics_with_NISS.csv")
demographics_niss_df

,PcrKey,ED Disposition,Hospital Disposition,Gender,Age,Race,niss,Severity,Final Mortality
0,225786099.0,Lived,Lived,Male,66.0,Black or African American,0.0,Mild/Moderate,Lived
1,225800981.0,Lived,Lived,Male,30.0,Black or African American,0.0,Mild/Moderate,Lived
2,225968094.0,Lived,Lived,Male,70.0,White,0.0,Mild/Moderate,Lived
3,226135057.0,Lived,Lived,Male,20.0,7701003,0.0,Mild/Moderate,Lived
4,226135240.0,Lived,Lived,Male,41.0,White,0.0,Mild/Moderate,Lived
...,...,...,...,...,...,...,...,...,...
7092,289247665.0,Lived,Died,Female,64.0,White,0.0,Mild/Moderate,Died
7093,289251627.0,Lived,Lived,Male,62.0,Hispanic or Latino,0.0,Mild/Moderate,Lived
7094,289252841.0,Lived,Lived,Female,37.0,Black or African American,0.0,Mild/Moderate,Lived
7095,289260113.0,Lived,Lived,Male,42.0,Hispanic or Latino,0.0,Mild/Moderate,Lived
7096,289267811.0,Lived,Lived,Male,41.0,Hispanic or Latino,0.0,Mild/Moderate,Lived

In [4]:
# Calculate the 95th percentile (top 5 percentile) of the 'niss' scores
top_5_percentile = demographics_niss_df['niss'].quantile(0.95)

print(f"The top 5 percentile (95th percentile) of NISS scores is: {top_5_percentile}")

The top 5 percentile (95th percentile) of NISS scores is: 0.0

In [8]:
# Count the number of non-zero NISS scores
non_zero_niss_count = (demographics_niss_df['niss'] != 0).sum()

print(f"The number of non-zero NISS scores is: {non_zero_niss_count}")

The number of non-zero NISS scores is: 18